[listen]
    udp_workers = 0
#    [[listen.udp]]
#        ip = '0.0.0.0'
#        port = 6969
#    [[listen.tcp]]
#        ip = '0.0.0.0'
#        port = 6969
    [[listen.tcp_udp]]
        ip = '0.0.0.0'
        port = 6969

redirect_url = ''