## General configuration
retry_interval = 20
sys_interval = 10
max_inflight_messages = 20
max_queued_messages = 100
queue_qos0_messages = false
message_size_limit = 0
allow_zero_length_clientid = true
auto_id_prefix = ''
persistent_client_expiration = ''
allow_duplicate_messages = false
upgrade_outgoing_qos = false

## Default listener
bind_address = '0.0.0.0'
port = 1883
max_connections = -1
use_username_as_clientid = false

## Persistence
autosave_interval = 1800
autosave_on_changes = false
persistence = false
persistence_file = 'mosquitto.db'
persistence_location = ''

## Logging
log_dest = 'stdout'
log_facility = ''
log_types = []
connection_messages = true
log_timestamp = true

## Security
clientid_prefixes = ''
allow_anonymous = true
use_password_file = false
use_psk_file = false
use_acl_file = false

## Bridges

# The following lists all available properties for bridges
#[[bridge]]
#    connection = 'myconnection'
#    addresses = ['another-broker:1883']
#    protocol_version = 'mqttv31'
#    attempt_unsubscribe = true
#    round_robin = false
#    remote_clientid = ''
#    local_clientid = ''
#    clean_session = false
#    notifications = true
#    notification_topic = ''
#    keepalive_interval = 60
#    start_type = 'automatic'
#    restart_timeout = 30
#    idle_timeout = 60
#    threshold = 10
#    try_private = true
#    remote_username = ''
#    remote_password = ''
#    [[bridge.topic]]
#        name = '/my/super/topic'
#        direction = 'out'
#        qos_level = 0
#        local_prefix = ''
#        remote_prefix = ''